sudo: required
services:
    - docker
before_install:
    - docker build -t josh2205/docker-react -f Dockerfile.dev .
script:
    - docker run -e CI=true josh2205/docker-react npm run test
deploy:
    provider: elasticbeanstalk
    region: "eu-west-2"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-eu-west-2-594228049577"
    bucket_path: "docker-react"
    on:
        branch: master